#Trendy package
```{r}
if (!requireNamespace("BiocManager", quietly=TRUE))
  install.packages("BiocManager")
BiocManager::install("Trendy")

library(Trendy)

BiocManager::install("ABAData")
library(ABAData)

BiocManager::install("ABAEnrichment")
library(ABAEnrichment)

library(biomaRt)
```


```{r}
listMarts(host = "https://www.ensembl.org", port = 443)

ensembl <- useMart(biomart = 'ENSEMBL_MART_ENSEMBL', 
                        dataset = 'hsapiens_gene_ensembl',
                        host = 'https://grch37.ensembl.org', port=443)

resP=getBM(attributes = c("hgnc_symbol","gene_biotype"),
              filters = "biotype",
              values = list(biotype="protein_coding"), mart = ensembl)
##Akey Deserts coordinates (Ensembl 1-based):
filterlist <- c("1:105400000:120600000", "3:74100000:89300000", "7:106200000:123200000","8:49400000:66500000")
##Select only protein-coding from Akey
results=getBM(attributes = c("hgnc_symbol", "chromosome_name", "start_position", "end_position","gene_biotype"),
              filters = c("chromosomal_region","biotype"),
              values = list(chromosomal_region=filterlist,biotype="protein_coding"), mart = ensembl)
results <- results[!duplicated(results$hgnc_symbol),]
#255
length(results$hgnc_symbol[!(is.na(results$hgnc_symbol) | results$hgnc_symbol=="")])
results <-  results[!(is.na(results$hgnc_symbol) | results$hgnc_symbol==""), ] #Cleaning

##Pey coordinates (Ensembl 1-based):
pey_coords <- read.delim("~/desertsHomo/1.data/input_data/2020_pey_coords.bed", header=FALSE) #File with start 0-based
###Preparing bed file for input in bioMart
pey_coords$V1 <- gsub("chr", "\\1", pey_coords$V1)
pey_coords[2] <- pey_coords[2]+1 #Moving to 1-based for Ensembl
df <- paste(pey_coords$V1, pey_coords$V2, pey_coords$V3, sep = ":")
results_pey=getBM(attributes = c("hgnc_symbol", "chromosome_name", "start_position", "end_position","gene_biotype"),
              filters = c("chromosomal_region","biotype"),
              values = list(chromosomal_region=df,biotype="protein_coding"), mart = ensembl)
results_pey <- results_pey[!duplicated(results_pey$hgnc_symbol),]

###Genes within Akey and Pey - RESULT
both <- results_pey[results_pey$hgnc_symbol %in% results$hgnc_symbol,]
both <-  both[!(is.na(both$hgnc_symbol) | both$hgnc_symbol==""), ] #Cleaning
```


#Data processing for TRENDY
##ABADATA
```{r}
##Loading dataset
data("dataset_5_stages")
#unique(dataset_5_stages$structure) #Checking structures

#Selecting genes ID and structures present in dataset
id <- unique(dataset_5_stages$ensembl_gene_id)
st <- unique(dataset_5_stages$structure)
st_allen <- paste("Allen",st, sep=":") 
#Expression data for all structures and genes
ab <- get_expression(structure_ids=st_allen, gene_ids = id, dataset='5_stages')

#Converting data to a dataframe with useful format for later
list1 = vector(mode="list")
for (r in 1:length(ab)){
  ab[[r]] <- t(ab[[r]]) #transpose
  list1 <- get_name(colnames(ab[[r]])) #change Allen:XXXX to e.g. M1C_primary motor cortex, etc
  colnames(ab[[r]]) <- list1
  ab[[r]] <- as.data.frame(ab[[r]])
}

ab1 = vector(mode="list", length = length(ab))
for (i in 1:length(ab)){
  for (h in 1:length(names(ab[[i]]))){
    ab1[[i]][[h]] <- ab[[i]][h]
  }
}

for (i in 1:length(ab)){
  for (h in 1:length(names(ab[[i]]))){
    G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id", "hgnc_symbol"),values=rownames(ab1[[i]][[h]]),mart=ensembl)
    ab1[[i]][[h]]['gene_name'] <-  G_list$hgnc_symbol[match(rownames(ab1[[i]][[h]]), G_list$ensembl_gene_id)]
    ab1[[i]][[h]] <-ab1[[i]][[h]][order(ab1[[i]][[h]][[1]], decreasing = TRUE), ]
  }
}

saveRDS(ab1, file = "~/desertsHomo/1.data/input_data/ABAdata_Trendy.rds")


ab1 <- readRDS(file = "~/desertsHomo/1.data/input_data/ABAdata_Trendy.rds")
```



#CEREBELLUM
```{r}
ab_1 <- as.data.frame(cbind(ab1[[1]][[16]]))
ab_1 <- ab_1[!(is.na(ab_1$gene_name) | ab_1$gene_name==""), ]
rownames(ab_1) <- NULL
colnames(ab_1)[1] <- "CBC_1"

ab_2 <- as.data.frame(cbind(ab1[[2]][[16]]))
ab_2 <- ab_2[!(is.na(ab_2$gene_name) | ab_2$gene_name==""), ]
rownames(ab_2) <- NULL
colnames(ab_2)[1] <- "CBC_2"

ab_3 <- as.data.frame(cbind(ab1[[3]][[16]]))
ab_3 <- ab_3[!(is.na(ab_3$gene_name) | ab_3$gene_name==""), ]
rownames(ab_3) <- NULL
colnames(ab_3)[1] <- "CBC_3"

ab_4 <- as.data.frame(cbind(ab1[[4]][[16]]))
ab_4 <- ab_4[!(is.na(ab_4$gene_name) | ab_4$gene_name==""), ]
rownames(ab_4) <- NULL
colnames(ab_4)[1] <- "CBC_4"


ab_5 <- as.data.frame(cbind(ab1[[5]][[16]]))
ab_5 <- ab_5[!(is.na(ab_5$gene_name) | ab_5$gene_name==""), ]
rownames(ab_5) <- NULL
colnames(ab_5)[1] <- "CBC_5"

library(dplyr)
aabb  <- right_join(ab_1, ab_2, by = "gene_name")
aabb  <- right_join(aabb, ab_3, by = "gene_name")
aabb  <- right_join(aabb, ab_4, by = "gene_name")
aabb  <- right_join(aabb, ab_5, by = "gene_name")
aabb <- aabb[!(is.na(aabb$gene_name) | aabb$gene_name==""), ]
rownames(aabb) <- aabb$gene_name
aabb$gene_name<- NULL

time.vector <- c(rep(1:5))

colnames(aabb) <- time.vector 
set.seed(10)
res_alt <- trendy(Data = aabb, tVectIn = time.vector, maxK = 2, minNumInSeg = 1, meanCut = 2)



res_alt <- results(res_alt)
res_alt.top <- topTrendy(res_alt)

#Good fit in Des & Pos sel.
rownames(res_alt.top$Trends)[rownames(res_alt.top$Trends) %in% both$hgnc_symbol]

res_alt.trend <- trendHeatmap(res_alt.top)

rcbc_aba <- as.data.frame(res_alt.top$AdjustedR2)
names(rcbc_aba) <- "Cerebellar cortex - R2"
write.csv(rcbc_aba, file="~/desertsHomo/1.data/trendy_adjR2/CBC_GenesDesertPosSel_adjR2_ABA.csv", row.names = TRUE, quote=T)

##Heatmap homemade
library(pheatmap)
class(res_alt.top$Trends)
#pheatmap(res_alt.top$Trends, cluster_rows=FALSE, cluster_cols = FALSE, legend_breaks = c(-1,0,1), filename = "~/desertsHomo/2.plots/trendy_segmentedRegression/CBC_UpDown_Deserts_ABA.pdf")

sb_inDesPey <- res_alt.top$Trends[rownames(res_alt.top$Trends)[rownames(res_alt.top$Trends) %in% both$hgnc_symbol],]

pheatmap(sb_inDesPey, cluster_rows=FALSE, cluster_cols = FALSE, legend_breaks = c(-1,0,1),filename = "~/desertsHomo/2.plots/trendy_segmentedRegression/CBC_UpDown_DesertsPosSel_ABA.pdf")



pdf("~/desertsHomo/2.plots/trendy_segmentedRegression/CBC_GenesDesertsPosSel_ABA.pdf")
par(mfrow=c(3,2))
plot2 <- plotFeature(aabb,tVectIn = time.vector,featureNames = c("ST7", "ROBO2", "CADPS2", "GPR22", "BCAP29", "KCND2", "SLC16A1"), trendyOutData = res_alt, customLabels.x = c("Prenatal","Child","Adol."), xlab="")
dev.off()
```



#STRIATUM
```{r}
ab_1 <- as.data.frame(cbind(ab1[[1]][[13]]))
ab_1 <- ab_1[!(is.na(ab_1$gene_name) | ab_1$gene_name==""), ]
rownames(ab_1) <- NULL
colnames(ab_1)[1] <- "STR_1"

ab_2 <- as.data.frame(cbind(ab1[[2]][[13]]))
ab_2 <- ab_2[!(is.na(ab_2$gene_name) | ab_2$gene_name==""), ]
rownames(ab_2) <- NULL
colnames(ab_2)[1] <- "STR_2"

ab_3 <- as.data.frame(cbind(ab1[[3]][[13]]))
ab_3 <- ab_3[!(is.na(ab_3$gene_name) | ab_3$gene_name==""), ]
rownames(ab_3) <- NULL
colnames(ab_3)[1] <- "STR_3"

ab_4 <- as.data.frame(cbind(ab1[[4]][[13]]))
ab_4 <- ab_4[!(is.na(ab_4$gene_name) | ab_4$gene_name==""), ]
rownames(ab_4) <- NULL
colnames(ab_4)[1] <- "STR_4"

ab_5 <- as.data.frame(cbind(ab1[[5]][[13]]))
ab_5 <- ab_5[!(is.na(ab_5$gene_name) | ab_5$gene_name==""), ]
rownames(ab_5) <- NULL
colnames(ab_5)[1] <- "STR_5"


library(dplyr)
aabb  <- right_join(ab_1, ab_2, by = "gene_name")
aabb  <- right_join(aabb, ab_3, by = "gene_name")
aabb  <- right_join(aabb, ab_4, by = "gene_name")
aabb  <- right_join(aabb, ab_5, by = "gene_name")
aabb <- aabb[!(is.na(aabb$gene_name) | aabb$gene_name==""), ]
rownames(aabb) <- aabb$gene_name
aabb$gene_name<- NULL

time.vector <- c(rep(1:5))

colnames(aabb) <- time.vector 
set.seed(10)
res_alt <- trendy(Data = aabb, tVectIn = time.vector, maxK = 2, minNumInSeg = 1, meanCut = 2)



res_alt <- results(res_alt)
res_alt.top <- topTrendy(res_alt)

#Good fit in Des & Pos sel.
rownames(res_alt.top$Trends)[rownames(res_alt.top$Trends) %in% both$hgnc_symbol]

res_alt.trend <- trendHeatmap(res_alt.top)

rcbc_aba <- as.data.frame(res_alt.top$AdjustedR2)
names(rcbc_aba) <- "Cerebellar cortex - R2"
write.csv(rcbc_aba, file="~/desertsHomo/1.data/trendy_adjR2/CBC_GenesDesertPosSel_adjR2_ABA.csv", row.names = TRUE, quote=T)

##Heatmap homemade
library(pheatmap)
class(res_alt.top$Trends)
#pheatmap(res_alt.top$Trends, cluster_rows=FALSE, cluster_cols = FALSE, legend_breaks = c(-1,0,1), filename = "~/desertsHomo/2.plots/trendy_segmentedRegression/CBC_UpDown_Deserts_ABA.pdf")

sb_inDesPey <- res_alt.top$Trends[rownames(res_alt.top$Trends)[rownames(res_alt.top$Trends) %in% both$hgnc_symbol],]

pheatmap(sb_inDesPey, cluster_rows=FALSE, cluster_cols = FALSE, legend_breaks = c(-1,0,1),filename = "~/desertsHomo/2.plots/trendy_segmentedRegression/CBC_UpDown_DesertsPosSel_ABA.pdf")



pdf("~/desertsHomo/2.plots/trendy_segmentedRegression/CBC_GenesDesertsPosSel_ABA.pdf")
par(mfrow=c(3,2))
plot2 <- plotFeature(aabb,tVectIn = time.vector,featureNames = c("ST7", "ROBO2", "CADPS2", "GPR22", "BCAP29", "KCND2", "SLC16A1"), trendyOutData = res_alt, customLabels.x = c("Prenatal","Child","Adol."), xlab="")
dev.off()
```
